# resnet50 optimize config


optimize_type: op_fusion

one_file_path: /media/wanzai/File/model_and_cfg_and_ofmap_folder/model_and_cfg_zoo/model/todo/sam_encoder.one

opt_one_file_path: /media/wanzai/File/model_and_cfg_and_ofmap_folder/model_and_cfg_zoo/model/todo/opt_sam_encoder.one

calibrate_img_name_txt_path: /home/wanzai/桌面/img_name.txt

calibrate_img_folder: /media/wanzai/File/imageNet/

calibrate_img_num: 256

quant_type: kl

resize_shapes: [256, 256]
crop_shapes: [224, 224]
normal_mean: [0.485ff, 0.456ff, 0.406ff]
normal_std: [0.229f, 0.224f, 0.225f]
