//
// Created by wanzai on 24-7-17.
//

#ifndef ONENEW_OPS_HEAD_H

#include "add.h"
#include "argmax.h"
#include "avgpool.h"
#include "clip.h"
#include "concat.h"
#include "conv.h"
#include "conv_transpose.h"
#include "cos.h"
#include "div.h"
#include "einsum.h"
#include "erf.h"
#include "expand.h"
#include "flatten.h"
#include "gather.h"
#include "gelu.h"
#include "gemm.h"
#include "global_avgpool.h"
#include "grid_sample.h"
#include "hard_sigmoid.h"
#include "io.h"
#include "layer_normalization.h"
#include "leaky_relu.h"
#include "log.h"
#include "mat_mul.h"
#include "maxpool.h"
#include "mul.h"
#include "object_detect.h"
#include "pad.h"
#include "pose_detect.h"
#include "pow.h"
#include "reduce_max.h"
#include "reduce_sum.h"
#include "reduce_mean.h"
#include "relu.h"
#include "reshape.h"
#include "resize.h"
#include "segment.h"
#include "sigmoid.h"
#include "sin.h"
#include "slice.h"
#include "softmax.h"
#include "split.h"
#include "sqrt.h"
#include "squeeze.h"
#include "sub.h"
#include "transpose.h"
#include "tile.h"
#include "top_k.h"
#include "unsqueeze.h"


#define ONENEW_OPS_HEAD_H

#endif //ONENEW_OPS_HEAD_H
