# 0  description: this is runtime args of one new

onnx_file_path: /home/wanzai/桌面/model_and_cfg_and_ofmap_folder/model_and_cfg_zoo/model/onnx_model/yolov5s.onnx

# 1  follow args you need fill
do_preprocess4img: yes
do_postprocess4net: no
one_file_path: /home/wanzai/桌面/oneNew/test/model_daily_test/tmp_one_model_path/yolov5s/yolov5s.one
input_data_path: /home/wanzai/桌面/oneNew/imgs/src_img/dog.png
in_operand_name: images

dump_ifmap&ofmap: yes

dump_output4each_node: dump_tracing
ofmap_folder: /home/wanzai/桌面/oneNew/test/model_daily_test/tmp_ofmap_path/yolov5s/

# 2  you need fill follow args, if you want to do ostprocess and the net is classification
crop_shapes: [640, 640]
resize_shapes: [640, 640]
normal_mean: [0.0f, 0.0f, 0.0f]
normal_std: [1.0f, 1.0f, 1.0f]

cpu: 12400F
cpu_hw_info: 2.5g * 8thread * 8 (avx2 = 8 * float32)
hw_computing_power (GOPS): 160
model name: yolov5s
csv_file: /home/wanzai/桌面/oneNew/tools/timeline_tracing/yolov5s.csv


