# resnet50 tracing config

do_preprocess: true

do_postprocess: true

one_file_path: /home/wanzai/桌面/oneNew/model_zoo/one_model/resnet50.one

input_data_path: /home/wanzai/桌面/oneNew/imgs/src_img/dog.png

model_exc_type: perf_profiling

ofmap_folder: /home/wanzai/桌面/oneNew/model_zoo/one_model/resnet50/

postprocess_type: classify

# 2  you need fill follow args, if you want to do postprocess and the net is classify
resize_shapes: [256, 256]
crop_shapes: [224, 224]
normal_mean: [0.5f, 0.5f, 0.5f]
normal_std: [0.5f, 0.5f, 0.5f]

cpu: 12400F
cpu_hw_info: 2.5g * 8thread * 8 (avx2 = 8 * float32)
hw_computing_power (GOPS): 160
model name: resnet50
tracing_csv_path: /home/wanzai/桌面/oneNew/tools/perf_profiling/timeline_info/resnet50.csv

