# resnet50 runtime config

do_preprocess: true

do_postprocess: false

one_file_path: /home/wanzai/桌面/oneNew/test/model_daily_test/tmp_one_model_path/yolov5s/yolov5s.one

input_data_path: /home/wanzai/桌面/oneNew/imgs/src_img/dog.png

model_exc_type: perf_profiling

ofmap_folder: /media/wanzai/File/model_and_cfg_and_ofmap_folder/ofmap4debug/yolov5s/


# 2  you need fill follow args, if you want to do postprocess and the net is classify
crop_shapes: [640, 640]
resize_shapes: [640, 640]
normal_mean: [0.0f, 0.0f, 0.0f]
normal_std: [1.0f, 1.0f, 1.0f]

cpu: 12400F
cpu_hw_info: 2.5g * 8thread * 8 (avx2 = 8 * float32)
hw_computing_power (GOPS): 160
model name: mobilenet_v2
tracing_csv_path: /home/wanzai/桌面/oneNew/tools/perf_profiling/timeline_info/yolov5s.csv

