# 0  description: this is runtime args of one new

# 1  follow args you need fill
do_preprocess4img: yes
do_postprocess4net: yes
one_file_path: /home/wanzai/桌面/model_and_cfg_and_ofmap_folder/model_and_cfg_zoo/model/one_model/mobilevit_s.one
input_data_path: /home/wanzai/桌面/oneNew/imgs/src_img/dog.png
in_operand_name: input0

dump_output4each_node: yes
ofmap_folder: /home/wanzai/桌面/model_and_cfg_and_ofmap_folder/ofmap4debug/mobilevit_s/

# if you want to do postprocess, please fill this args classification or detection
postprocess_type: classification

# 2  you need fill follow args, if you want to do postprocess and the net is classification
resize_shapes: [256, 256]
crop_shapes: [224, 224]
normal_mean: [0.3281186, 0.28937867, 0.20702125]
normal_std: [22, 22, 22]
#normal_std: [23.975f, 24.8f, 27.2f]

# 3  you need fill follow args, if you want to do postprocess and the net is classification
topk: 5
