# 0  description: this is runtime args of one new

# 1  follow args you need fill
do_preprocess4img: yes
do_postprocess4net: yes
one_file_path: /home/wanzai/桌面/model_and_cfg_and_ofmap_folder/model_and_cfg_zoo/model/todo/resnet101.one
input_data_path: /home/wanzai/桌面/oneNew/imgs/src_img/dog.png
in_operand_name: input.1

dump_output4each_node: no
ofmap_folder: /home/wanzai/桌面/model_and_cfg_and_ofmap_folder/ofmap4debug/resnet101/

# if you want to do postprocess, please fill this args classification or detection
postprocess_type: classification

# 2  you need fill follow args, if you want to do postprocess and the net is classification
resize_shapes: [256, 256]
crop_shapes: [224, 224]
normal_mean: [0.485ff, 0.456ff, 0.406ff]
normal_std: [0.229f, 0.224f, 0.225f]

# 3  you need fill follow args, if you want to do postprocess and the net is classification
topk: 5



