# 0  description: this is runtime args of one new

# 1  follow args you need fill
do_preprocess4img: yes
do_postprocess4net: yes
one_file_path: /home/wanzai/桌面/model_and_cfg_and_ofmap_folder/model_and_cfg_zoo/model/todo/yolov5s.one
#one_file_path: /home/wanzai/桌面/model_and_cfg_and_ofmap_folder/model_and_cfg_zoo/model/one_model/yolov5s.one
input_data_path: /home/wanzai/桌面/oneNew/imgs/src_img/dog.png
in_operand_name: images
out_operand_name: /model.24/m.2/Conv_output_0;/model.24/m.1/Conv_output_0;/model.24/m.0/Conv_output_0

dump_output4each_node: yes
ofmap_folder: /home/wanzai/桌面/model_and_cfg_and_ofmap_folder/ofmap4debug/yolov5s/

# if you want to do postprocess, please fill this args classification or detection
postprocess_type: detection


# 2  you need fill follow args, if you want to do ostprocess and the net is classification
crop_shapes: [640, 640]
resize_shapes: [640, 640]
normal_mean: [0.0f, 0.0f, 0.0f]
normal_std: [1.0f, 1.0f, 1.0f]


# 4  you need fill follow args, if you want to do postprocess and the net is detection
detect_net: yolov5
ifmap_num: 3
anchor_num: 3
anchor_scale_table: [116, 90, 156, 198, 373, 326], [30, 61, 62, 5, 59, 119], [10, 13, 16, 30, 33, 23]
cls_num: 80
max_boxes_per_class: 100
max_boxes_per_batch: 210
score_threshold: 0.3f
iou_threshold: 0.7f

