# 0  description: this is runtime args of one new

# 1  follow args you need fill
do_preprocess4img: yes
do_postprocess4net: yes
one_file_path: /home/wanzai/桌面/model_and_cfg_and_ofmap_folder/model_and_cfg_zoo/model/one_model/yolov8m_pose.one
input_data_path: /home/wanzai/桌面/oneNew/imgs/src_img/xinxin2.jpg
in_operand_name: images
out_operand_name: onnx::Reshape_522;onnx::Reshape_507;onnx::Reshape_492;onnx::Reshape_468;onnx::Reshape_454;onnx::Reshape_440

dump_output4each_node: yes
ofmap_folder: /home/wanzai/桌面/model_and_cfg_and_ofmap_folder/ofmap4debug/yolov8m_pose/

# if you want to do postprocess, please fill this args classification or detection
postprocess_type: pose_detection

# 2  you need fill follow args, if you want to do ostprocess and the net is classification
crop_shapes: [640, 640]
resize_shapes: [640, 640]
normal_mean: [0.0f, 0.0f, 0.0f]
normal_std: [1.0f, 1.0f, 1.0f]

