# 0  description: this is runtime args of one new

# 1  follow args you need fill
one_file_path: /home/wanzai/桌面/model_and_cfg_and_ofmap_folder/model_and_cfg_zoo/model/one_model/yolov7.one
quant_one_file_path: /home/wanzai/桌面/model_and_cfg_and_ofmap_folder/model_and_cfg_zoo/model/one_model/optimize_yolov7.one


input_data_path: /home/wanzai/桌面/oneNew/imgs/src_img/dog.png
do_preprocess4img: yes
do_postprocess4net: no
in_operand_name: images
out_operand_name: /model.24/m.2/Conv_output_0;/model.24/m.1/Conv_output_0;/model.24/m.0/Conv_output_0
input_path: "aaa"
dump_output4each_node: yes
ofmap_folder: /home/wanzai/桌面/model_and_cfg_and_ofmap_folder/ofmap4debug/yolov7/

