# 0  description: this is runtime args of one new

### 1  follow args you need fill
#one_file_path: /home/wanzai/桌面/oneNew/tools/liu_resnet18.one
#quant_one_file_path: /home/wanzai/桌面/oneNew/tools/optimize_liu_resnet18.one

## 1  follow args you need fill
#one_file_path: /home/wanzai/桌面/oneNew/tools/liu_yolov8_seg.one
#quant_one_file_path: /home/wanzai/桌面/oneNew/tools/optimize_liu_yolov8_seg.one

## 1  follow args you need fill
#one_file_path: /home/wanzai/桌面/oneNew/tools/yolov8m_seg.one
#quant_one_file_path: /home/wanzai/桌面/oneNew/tools/optimize_yolov8m_seg.one

# 1  follow args you need fill
one_file_path: /home/wanzai/桌面/oneNew/tools/yolov8m_pose_export_6_tensor.one
quant_one_file_path: /home/wanzai/桌面/oneNew/tools/optimize_yolov8m_pose_export_6_tensor.one

