# resnet50 metrics config

do_preprocess: true

do_postprocess: true

one_file_path: /media/wanzai/File/model_and_cfg_and_ofmap_folder/model_and_cfg_zoo/model/onnx_model/resnet50.one

metrics_img_label_txt_path: /home/wanzai/桌面/img_name.txt

metrics_img_path: /media/wanzai/File/imageNet/

metrics_img_num: 1000

model_exc_type: efficient_exc

postprocess_type: classification

resize_shapes: [256, 256]
crop_shapes: [224, 224]
normal_mean: [0.485ff, 0.456ff, 0.406ff]
normal_std: [0.229f, 0.224f, 0.225f]


