# swin_t metrics config

do_preprocess: true

do_postprocess: true

one_file_path: /home/wanzai/桌面/oneNew/test/model_daily_test/tmp_one_model_path/swin_t/swin_t.one

metrics_img_label_txt_path: /home/wanzai/桌面/img_name.txt

metrics_img_path: /home/wanzai/桌面/imageNet/

metrics_img_num: 50000

model_exc_type: release

postprocess_type: classification

resize_shapes: [256, 256]
crop_shapes: [224, 224]
normal_mean: [0.5f, 0.5f, 0.5f]
normal_std: [0.5f, 0.5f, 0.5f]




