# resnet50 runtime config

do_preprocess: true

do_postprocess: false

one_file_path: /media/wanzai/File/model_and_cfg_and_ofmap_folder/model_and_cfg_zoo/model/todo/opt_clip_txt.one

clip_txt_one_file_path: /media/wanzai/File/model_and_cfg_and_ofmap_folder/model_and_cfg_zoo/model/todo/opt_clip_txt.one

token_list: [49406, 589, 533, 320, 1125, 539, 320, 1579, 4558, 49407, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

input_data_path: /home/wanzai/桌面/oneNew/imgs/src_img/dog.png

model_exc_type: ofmap_dumping

ofmap_folder: /media/wanzai/File/model_and_cfg_and_ofmap_folder/ofmap4debug/clip_txt/


resize_shapes: [256, 256]
crop_shapes: [224, 224]
normal_mean: [0.5f, 0.5f, 0.5f]
normal_std: [0.5f, 0.5f, 0.5f]


