# resnet50 runtime config

do_preprocess: true

do_postprocess: false


one_file_path: /media/wanzai/File/model_and_cfg_and_ofmap_folder/model_and_cfg_zoo/model/todo/opt_clip_img.one
img_folder_path: /home/wanzai/桌面/clip_model-img/
input_data_path: /home/wanzai/桌面/clip_model-img/dark_horse.jpeg

clip_txt_one_file_path: /media/wanzai/File/model_and_cfg_and_ofmap_folder/model_and_cfg_zoo/model/todo/opt_clip_txt.one

model_exc_type: release

ofmap_folder: /media/wanzai/File/model_and_cfg_and_ofmap_folder/ofmap4debug/clip/

resize_shapes: [256, 256]
crop_shapes: [224, 224]
normal_mean: [0.5f, 0.5f, 0.5f]
normal_std: [0.5f, 0.5f, 0.5f]


