# resnet50 runtime config

do_preprocess: true

do_postprocess: false

one_file_path: /media/wanzai/File/model_and_cfg_and_ofmap_folder/model_and_cfg_zoo/model/todo/mobilevit_s.one

input_data_path: /home/wanzai/桌面/oneNew/imgs/src_img/dog.png

model_exc_type: ofmap_dumping

ofmap_folder: /media/wanzai/File/model_and_cfg_and_ofmap_folder/ofmap4debug/mobilevit_s/

postprocess_type: classify

resize_shapes: [256, 256]
crop_shapes: [224, 224]
normal_mean: [0.485ff, 0.456ff, 0.406ff]
normal_std: [0.229f, 0.224f, 0.225f]

