# resnet50 runtime config

do_preprocess: true

do_postprocess: true

#one_file_path: /home/wanzai/桌面/oneNew/test/model_daily_test/tmp_one_model_path/yolo_world_cls14/yolo_world_cls14.one
#one_file_path: /home/wanzai/桌面/oneNew/test/model_daily_test/tmp_one_model_path/rt_detr/rt_detr.one
#one_file_path: /home/wanzai/桌面/oneNew/test/model_daily_test/tmp_one_model_path/yolov8m_pose/yolov8m_pose.one
one_file_path: /home/wanzai/桌面/oneNew/test/model_daily_test/tmp_one_model_path/yolov8n_seg/yolov8n_seg.one

#input_data_path: /media/wanzai/File/imageNet/ILSVRC2012_val_00000388.JPEG
#input_data_path: /home/wanzai/桌面/clip_model-img/ILSVRC2012_val_00001044.JPEG
input_data_path: /home/wanzai/桌面/oneNew/imgs/src_img/street.jpg
#input_data_path: /home/wanzai/桌面/oneNew/imgs/src_img/dog.png

model_exc_type: efficient_exc

ofmap_folder: /media/wanzai/File/model_and_cfg_and_ofmap_folder/ofmap4debug/yolov5s/

#postprocess_type: object_detect
#postprocess_type: pose_detect
postprocess_type: segment

resize_shapes: [640, 640]
crop_shapes: [640, 640]
normal_mean: [0.0f, 0.0f, 0.0f]
normal_std: [1.0f, 1.0f, 1.0f]

net_type: yolo_world
cls_num: 80
score_threshold: 0.3
iou_threshold: 0.6
