# resnet50 runtime config

do_preprocess: true

do_postprocess: false

one_file_path: /home/wanzai/桌面/oneNew/test/model_daily_test/tmp_one_model_path/rt_detr/rt_detr.one

input_data_path: /home/wanzai/桌面/oneNew/imgs/src_img/dog.png

model_exc_type: debug

ofmap_folder: /media/wanzai/File/model_and_cfg_and_ofmap_folder/ofmap4debug/rt_detr/


resize_shapes: [640, 640]
crop_shapes: [640, 640]
normal_mean: [0.0f, 0.0f, 0.0f]
normal_std: [1.0f, 1.0f, 1.0f]


cpu: 12400F
cpu_hw_info: 2.5g * 8thread * 8 (avx2 = 8 * float32)
hw_computing_power (GOPS): 160
model name: rt_detr
tracing_csv_path: /home/wanzai/桌面/oneNew/tools/tracing/timeline_info/rt_detr.csv

