# resnet50 runtime config

do_preprocess: true

do_postprocess: false

#one_file_path: /media/wanzai/File/model_and_cfg_and_ofmap_folder/model_and_cfg_zoo/model/todo/opt_sam_encoder.one
one_file_path: /media/wanzai/File/model_and_cfg_and_ofmap_folder/model_and_cfg_zoo/model/todo/sam_encoder.one

input_data_path: /home/wanzai/桌面/oneNew/imgs/src_img/dog.png

model_exc_type: ofmap_dumping

ofmap_folder: /media/wanzai/File/model_and_cfg_and_ofmap_folder/ofmap4debug/sam_encoder/


resize_shapes: [1024, 1024]
crop_shapes: [1024, 1024]
normal_mean: [0.0f, 0.0f, 0.0f]
normal_std: [1.0f, 1.0f, 1.0f]


cpu: 12400F
cpu_hw_info: 2.5g * 8thread * 8 (avx2 = 8 * float32)
hw_computing_power (GOPS): 160
model name: sam_encoder
tracing_csv_path: /home/wanzai/桌面/oneNew/tools/perf_profiling/timeline_info/sam_encoder.csv

